# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('concentration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MotionSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('motion_detected', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureHumiditySensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
    ]
